### ISSUE TITLE
HuduAPI 2.2

### ISSUE THREAD

**Issue by smm080808** [lwhitelock/HuduAPI#15]
Hello,

I am using your Hudu API powershell module and it is awesome!  Thanks for the hard work.

Can you update this to allow passwords to be updates/created into password folders?
password_folder_id is an available field... Hudu support confirmed...  It does not work in the API 2.2 I am using.

![image](https://user-images.githubusercontent.com/116727388/198020202-cb466f2e-b727-4ac6-87fb-caa2bdc131ef.png)

**Comment by johnduprey** [comment]
Implemented in #25
