### ISSUE TITLE
[BUG]Get-HuduAssets '-Name' parameter doesn't deal with special characters.

### ISSUE THREAD

**Issue by jmartncp** [lwhitelock/HuduAPI#22]
If you attempt to find asset(s) by name with the `Get-HuduAssets` command, passing in a name that contains a special character such as `&`, the results will never be accurate. I suspect the following portion of the source code to be responsible for this strange behavior:
![image](https://user-images.githubusercontent.com/102254299/213251794-bd53108c-c718-4f2d-b317-6e08649eadb8.png)

It is just interpolating the name into the string without taking into account the need for encoding. Thanks for reading.

**Comment by palonix-seth** [comment]
This same issue also exists with Get-HuduCompanies -Name

You can do Get-HuduAssets | ?{$_.Name -eq $AssetName} instead, same with Get-HuduCompanies or any of the other ones that have this issue. I'd imagine there are a handful of the Get- that are like this if the Hudu API doesn't directly support passing a name.

Each of the variables just needs [uri]::EscapeDataString($variable), example:
```
if ($Name) {
	$ResourceFilter = "$($ResourceFilter)&name=$([uri]::EscapeDataString($Name))"
}
```
