### ISSUE TITLE
Using a Company Scope API key will fail "Get-HuduAssets"

### ISSUE THREAD

**Issue by dvir001** [lwhitelock/HuduAPI#28]
The command to create a new asset working as normal (New-HuduAsset) but the command to get information about assets wont work.

This issue exists with company Scope API keys only, not on global keys.

You can test it:
New-HuduAPIKey $HuduAPIKey # Api for Company Scope
New-HuduBaseUrl $huduDomain

$huduAssetName = "Test"
$company_id = "" # ID for the company in that api scope

Get-HuduAssets -name $huduAssetName -company_id $huduCompanyID -asset_layout_id $huduLayoutID
Get-HuduAssets -name $huduAssetName
Get-HuduAssets -company_id $huduCompanyID -asset_layout_id $huduLayoutID
Get-HuduAssets

All of the commands with Get-HuduAssets return the same error:

`ERROR: Invoke-HuduRequest : '{"status":500,"error":"Internal Server Error"}'
HuduAPI.psm1 (368, 14): ERROR: At Line: 368 char: 14
ERROR: + ...   $Assets = Invoke-HuduRequest -Method get -Resource "/api/v1/assets? ...
ERROR: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR:     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
ERROR:     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-HuduRequest`

**Comment by greenlighttec** [comment]
From memory, this is an API issue and NOT a Module issue. Using scoped API keys will not allow you to retrieve all assets and then filter for a specific company.

Getting an Asset with a scoped API key requires you to hit GET api/v1/companies/:company_id/assets

Whereas GET api/v1/assets and passing in the company id will fail for an API Key that is scoped globally. 

There may be a way we can account for this, or include a parameter indicating the API Key is limited so that we switch endpoints.

**Comment by dvir001** [comment]
Thanks for the fast respond,

This seems to be the issue, not sure how to fix it myself, but im assuming it will require a change to the code on that command to resolve it.

**Comment by greenlighttec** [comment]
It will require a change in code yes, for right now can you test by running 

`Invoke-HuduRequest -Method GET -Resource "/api/v1/companies/$companyid/assets"`

And see if you get back assets for the company? If so you can use that as a workaround until we code it in.

**Comment by dvir001** [comment]
It works by giving all the assets yes, 
But there no option for the search query on it.

**Comment by greenlighttec** [comment]
Looking at the Hudu documentation, there's no filtering options available. You'll need to load it all into a PowerShell variable and then PowerShell filters to get what you need. i.e. (something like this)

```
$CompanyAssets = Invoke-HuduRequest -Method GET -Resource "/api/v1/companies/$companyid/assets"
$ComputerAssets = $CompanyAssets.assets |? {$_.asset_layout_id -eq 2}
```

We can probably recreate this into an easy-to-use function at some point but it is a lot of work to do.

Also, the Pseudo code is completely off the top of my head, so you'll likely have to figure out the real syntax and specifics.

**Comment by dvir001** [comment]
Managed to get it to work

`
        $i = 1;
	$AllAssets = do
	{
		$Assets = Invoke-HuduRequest -Method get -Resource "/api/v1/companies/$huduCompanyID/assets?page=$i&page_size=1000"
		$i++
		$Assets.Assets
	}
	while ($Assets.Assets.count % 1000 -eq 0 -and $Assets.Assets.count -ne 0)
	
	$huduAsset = $AllAssets | Where-Object { ($_.asset_layout_id -eq $huduLayoutID) -and ($_.name -eq $huduAssetName) }
`

It working to test if an asset exists now and working great.

**Comment by greenlighttec** [comment]
Ok awesome! Yeah I forgot about paging 😄

**Comment by greenlighttec** [comment]
I raised support request 17927 in case they can update their API and we don't have to do anything 😃

**Comment by greenlighttec** [comment]
Confirmed working with the latest API Changes. Closing
