### ISSUE TITLE
Get-HuduWebsites 'id' cannot be specified

### ISSUE THREAD

**Issue by matsax** [lwhitelock/HuduAPI#6]
Getting this error when using Get-HuduWebsites
The parameter 'id' cannot be specified because it conflicts with the parameter alias of the same name for parameter
'WebsiteId'.
At line:1 char:1
+ Get-HuduWebsites
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], MetadataException
    + FullyQualifiedErrorId : ParameterNameConflictsWithAlias

**Comment by lwhitelock** [comment]
Fixed this now in version 1.22 thanks for letting me know!
